### ISSUE TITLE
Tempo di volo

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/volo#1]
Utilizzando il linguaggio Python si scriva
un programma volo.py

```python
# determinare la durata massima di volo conoscendo
# la quantita' di carburante ed il consumo orario

carburante = 1460. # galloni USA
consumo_h = 320. # galloni USA / h
```

**Comment by FabioZTessitore** [comment]
a cosa serve un'istruzione del genere?
```py
int(consumotot)
```

**Comment by CarloRuzzon** [comment]
Per rendere consumotot un intero ed eliminare i decimali indesiderati

Il 24 nov 2016 1:10 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
e funziona anche se il risultato di questa operazione non viene memorizzato da nessuna parte?

**Comment by CarloRuzzon** [comment]
Funziona e basta.

Il 24 nov 2016 2:13 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
cerca di fare un programma decente o niente passaggio alla gialla

**Comment by CarloRuzzon** [comment]
ma ci servono gli if?

**Comment by FabioZTessitore** [comment]
No

Il martedì 29 novembre 2016, CarloRuzzon <notifications@github.com> ha
scritto:

**Comment by CarloRuzzon** [comment]
Sono ripartito da capo con le vostre informazioni iniziali, va bene?
